name: All Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Packages
        run: |
          nix develop --command make build

      - name: Run Tests
        run: |
          output=$(DEBUG_LEVEL=trace nix develop --command make test | tee >(cat >&2))
          passing=$(echo "$output" | grep -oP '\d+ passing' | grep -oP '\d+' || echo 0)
          failing=$(echo "$output" | grep -oP '\d+ failing' | grep -oP '\d+' || echo 0)
          pending=$(echo "$output" | grep -oP '\d+ pending' | grep -oP '\d+' || echo 0)
          echo "## Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Passed   | Failed   | Pending  |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|----------|----------|" >> $GITHUB_STEP_SUMMARY
          echo "| $passing | $failing | $pending |" >> $GITHUB_STEP_SUMMARY
          if [ "$failing" -ne 0 ]; then exit 1; fi
